### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by dhymasriyanto** [lukas-reineke/onedark.nvim#2]
Sorry, I'm new to NVim, can you explain how to use this theme configuration to integrate with indent-blankline? Thanks!

**Comment by lukas-reineke** [comment]
I made this for my personal use, so I didn't follow normal colorsheme conventions.
It might do some unexpected things, and I will push breaking changes from time to time.

There are other onedark nvim themes that are probably better to use, like https://github.com/navarasu/onedark.nvim

But if you want to use this, go ahead :+1: 
You just need to install it and run `require("onedark").setup()` and it should work.

**Comment by dhymasriyanto** [comment]
Thanks for ur guide and thanks for ur recommendation!
